# kustomize/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: your-dockerhub-username/sample-app
    newTag: "latest"

configMapGenerator:
  - name: app-config
    literals:
      - ENV=production
